language: node_js

node_js:
- '0.12'

addons:
  sauce_connect: true

env:
  global:
  - secure: eiS4pjd/UxmCuELg0Zxv4gKoTsYpSX8NumlzjO/u2blc3mExFI0rChflQ6a0RG5JveZJBI5GBH2j5sI7A/UpBZDun4WUS6NVylteWSwYuEvHaMeg/m9PdlDuAwvLggrHDdlEjwz6mFynixscOTeCTPHjT5Nv812/91/+CGBYNqMmg9sqPWTkR9UwRGjSWdKWYX3y/HtPk6zfoY9OtkeCsTn5wu1TJQV76G5r4Bo5trr2qGNVuMIgD2gRPHBhnSzM0LxG+IR7erJ5wdbvDZO6NhLFIOFIq+NQ/l1JLNjqDm8Tum3bXlJVQlyMHypUOpdxOl+M4jiz0ZIz0PzMXBPkiAbjH9tBfeHHpfO1Cwh6dM7iK6FQqgqsjVrgORoeYGIncJN4ct2Pi/4tkxa+DMZoxv+q2vPkDnwAwDkf77PYKTRCoxmCU7rE9wkCaC0MpE+g2Vvmm7sYLpUclTmknipdM/IJPkdh1u2PMfJ/vR+/AqACsvaSdf1lZXLWTU83zwclNci2oXhhMfbTGTp+YKfB6P3o9zRo1x8+nAnrHAQ6v1CkNTNy4bUshqVcybrzFZkOlNX52lb3NbPiT4qmqDvHwIB9RBCu5tClY50cfTimx4vNuo1ZDpT6y6rrbf8KBZbygcIi3o3RKpfuow5ppmCx7rkaNrJz62WKR5dv/GzzOwg=
  - secure: IdWnoryGFLoCw2zqmcxG9xRM+TLXgB4BxWwJa7SeJXzlaWJrcCGmVcRyEeT2FjfcZRGTFrETq/tioHAS0VZKSeefAeVgWuJa2RFLiUowcRtFnAWQE4lfxS8KxRXVq6cCuRFQ+iEzcsOQOxVsJoNTZcz6cmPe+FF3cI58ZLGTNqg/p2fxhmQJ13P7vCu2PEOCvzvxjjUy/+L4gINIq/RmFsDrGX1Dbh1cJzOLMtXFbvW1VlhKq9he2GNS5JJUFdeqD8k6/tolm1NgHx7fG3HCZ6cm1lkJAYE9D8093fttGNbJXr7HyDoSBxBGQcLtnVI5Mezym72pcEVeWp3GLWD7u9DpJCKqY0mvg5Kv25Ot7qvgYQazdH6kFIzt9eqWcDMvuIiq9vhp8rG5hwtuUKcrNclIZF3y4q9Z+u2eyVGbCNmvPc49H/tL4RlOaBTbIlJBIgPpbOTtZdzPmIUgjUhI1ekG6rk26sTUYl05iWrC9noOo1nhpQ7Hg5dti+ftImZk+SY3Ro+DxupXx+H5L63mPXru1qfRA4+4+f5aHB37fdkutCsddEXvJuMKOy1QV5ofpuYGO8CD5dILbO/fXsr6iCIg0HBJ0mO+dE6TOnu/luTZvKxGvKgHYx9usxAhMwpsYfhEnqfh213ajt+7zqR0phtL02rX+Lt5OkUIAKDX8K0=
